version: "3.7"

services: 
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 3012:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=decode
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: carrental
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local