version: "3.7"

services: 
  database_ignite:
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=decode
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: carrental
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local